name: Build HoneyBadger.Client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup dotnet 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Run server
      run: docker run -d -p 18950:18950  meeron/honey-badger:latest
    - name: Build & test
      run: make test c=Debug
